###############################################################################
# Created by write_sdc
###############################################################################
current_design soc_top
###############################################################################
# Timing Constraints
###############################################################################
create_clock -name clk -period 10.0000 [get_ports {clk}]
set_clock_transition 0.1500 [get_clocks {clk}]
set_clock_uncertainty 0.2500 clk
set_propagated_clock [get_clocks {clk}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {reset}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {Hsync}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {Vsync}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {blue[0]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {blue[1]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {blue[2]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {blue[3]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {blue[4]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {blue[5]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {blue[6]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {blue[7]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {cpu_stall}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {display_enable}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {green[0]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {green[1]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {green[2]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {green[3]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {green[4]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {green[5]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {green[6]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {green[7]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {mem_addr[0]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {mem_addr[10]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {mem_addr[11]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {mem_addr[12]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {mem_addr[13]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {mem_addr[14]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {mem_addr[15]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {mem_addr[16]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {mem_addr[17]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {mem_addr[18]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {mem_addr[19]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {mem_addr[1]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {mem_addr[20]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {mem_addr[21]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {mem_addr[22]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {mem_addr[23]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {mem_addr[24]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {mem_addr[25]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {mem_addr[26]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {mem_addr[27]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {mem_addr[28]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {mem_addr[29]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {mem_addr[2]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {mem_addr[30]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {mem_addr[31]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {mem_addr[3]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {mem_addr[4]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {mem_addr[5]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {mem_addr[6]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {mem_addr[7]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {mem_addr[8]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {mem_addr[9]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {mem_read}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {mem_wdata[0]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {mem_wdata[10]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {mem_wdata[11]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {mem_wdata[12]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {mem_wdata[13]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {mem_wdata[14]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {mem_wdata[15]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {mem_wdata[16]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {mem_wdata[17]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {mem_wdata[18]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {mem_wdata[19]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {mem_wdata[1]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {mem_wdata[20]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {mem_wdata[21]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {mem_wdata[22]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {mem_wdata[23]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {mem_wdata[24]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {mem_wdata[25]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {mem_wdata[26]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {mem_wdata[27]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {mem_wdata[28]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {mem_wdata[29]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {mem_wdata[2]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {mem_wdata[30]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {mem_wdata[31]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {mem_wdata[3]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {mem_wdata[4]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {mem_wdata[5]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {mem_wdata[6]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {mem_wdata[7]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {mem_wdata[8]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {mem_wdata[9]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {mem_write}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {pcRegister[0]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {pcRegister[10]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {pcRegister[11]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {pcRegister[12]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {pcRegister[13]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {pcRegister[14]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {pcRegister[15]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {pcRegister[16]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {pcRegister[17]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {pcRegister[18]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {pcRegister[19]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {pcRegister[1]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {pcRegister[20]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {pcRegister[21]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {pcRegister[22]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {pcRegister[23]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {pcRegister[24]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {pcRegister[25]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {pcRegister[26]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {pcRegister[27]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {pcRegister[28]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {pcRegister[29]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {pcRegister[2]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {pcRegister[30]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {pcRegister[31]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {pcRegister[3]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {pcRegister[4]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {pcRegister[5]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {pcRegister[6]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {pcRegister[7]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {pcRegister[8]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {pcRegister[9]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {red[0]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {red[1]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {red[2]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {red[3]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {red[4]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {red[5]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {red[6]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {red[7]}]
###############################################################################
# Environment
###############################################################################
set_load -pin_load 0.0334 [get_ports {Hsync}]
set_load -pin_load 0.0334 [get_ports {Vsync}]
set_load -pin_load 0.0334 [get_ports {cpu_stall}]
set_load -pin_load 0.0334 [get_ports {display_enable}]
set_load -pin_load 0.0334 [get_ports {mem_read}]
set_load -pin_load 0.0334 [get_ports {mem_write}]
set_load -pin_load 0.0334 [get_ports {blue[7]}]
set_load -pin_load 0.0334 [get_ports {blue[6]}]
set_load -pin_load 0.0334 [get_ports {blue[5]}]
set_load -pin_load 0.0334 [get_ports {blue[4]}]
set_load -pin_load 0.0334 [get_ports {blue[3]}]
set_load -pin_load 0.0334 [get_ports {blue[2]}]
set_load -pin_load 0.0334 [get_ports {blue[1]}]
set_load -pin_load 0.0334 [get_ports {blue[0]}]
set_load -pin_load 0.0334 [get_ports {green[7]}]
set_load -pin_load 0.0334 [get_ports {green[6]}]
set_load -pin_load 0.0334 [get_ports {green[5]}]
set_load -pin_load 0.0334 [get_ports {green[4]}]
set_load -pin_load 0.0334 [get_ports {green[3]}]
set_load -pin_load 0.0334 [get_ports {green[2]}]
set_load -pin_load 0.0334 [get_ports {green[1]}]
set_load -pin_load 0.0334 [get_ports {green[0]}]
set_load -pin_load 0.0334 [get_ports {mem_addr[31]}]
set_load -pin_load 0.0334 [get_ports {mem_addr[30]}]
set_load -pin_load 0.0334 [get_ports {mem_addr[29]}]
set_load -pin_load 0.0334 [get_ports {mem_addr[28]}]
set_load -pin_load 0.0334 [get_ports {mem_addr[27]}]
set_load -pin_load 0.0334 [get_ports {mem_addr[26]}]
set_load -pin_load 0.0334 [get_ports {mem_addr[25]}]
set_load -pin_load 0.0334 [get_ports {mem_addr[24]}]
set_load -pin_load 0.0334 [get_ports {mem_addr[23]}]
set_load -pin_load 0.0334 [get_ports {mem_addr[22]}]
set_load -pin_load 0.0334 [get_ports {mem_addr[21]}]
set_load -pin_load 0.0334 [get_ports {mem_addr[20]}]
set_load -pin_load 0.0334 [get_ports {mem_addr[19]}]
set_load -pin_load 0.0334 [get_ports {mem_addr[18]}]
set_load -pin_load 0.0334 [get_ports {mem_addr[17]}]
set_load -pin_load 0.0334 [get_ports {mem_addr[16]}]
set_load -pin_load 0.0334 [get_ports {mem_addr[15]}]
set_load -pin_load 0.0334 [get_ports {mem_addr[14]}]
set_load -pin_load 0.0334 [get_ports {mem_addr[13]}]
set_load -pin_load 0.0334 [get_ports {mem_addr[12]}]
set_load -pin_load 0.0334 [get_ports {mem_addr[11]}]
set_load -pin_load 0.0334 [get_ports {mem_addr[10]}]
set_load -pin_load 0.0334 [get_ports {mem_addr[9]}]
set_load -pin_load 0.0334 [get_ports {mem_addr[8]}]
set_load -pin_load 0.0334 [get_ports {mem_addr[7]}]
set_load -pin_load 0.0334 [get_ports {mem_addr[6]}]
set_load -pin_load 0.0334 [get_ports {mem_addr[5]}]
set_load -pin_load 0.0334 [get_ports {mem_addr[4]}]
set_load -pin_load 0.0334 [get_ports {mem_addr[3]}]
set_load -pin_load 0.0334 [get_ports {mem_addr[2]}]
set_load -pin_load 0.0334 [get_ports {mem_addr[1]}]
set_load -pin_load 0.0334 [get_ports {mem_addr[0]}]
set_load -pin_load 0.0334 [get_ports {mem_wdata[31]}]
set_load -pin_load 0.0334 [get_ports {mem_wdata[30]}]
set_load -pin_load 0.0334 [get_ports {mem_wdata[29]}]
set_load -pin_load 0.0334 [get_ports {mem_wdata[28]}]
set_load -pin_load 0.0334 [get_ports {mem_wdata[27]}]
set_load -pin_load 0.0334 [get_ports {mem_wdata[26]}]
set_load -pin_load 0.0334 [get_ports {mem_wdata[25]}]
set_load -pin_load 0.0334 [get_ports {mem_wdata[24]}]
set_load -pin_load 0.0334 [get_ports {mem_wdata[23]}]
set_load -pin_load 0.0334 [get_ports {mem_wdata[22]}]
set_load -pin_load 0.0334 [get_ports {mem_wdata[21]}]
set_load -pin_load 0.0334 [get_ports {mem_wdata[20]}]
set_load -pin_load 0.0334 [get_ports {mem_wdata[19]}]
set_load -pin_load 0.0334 [get_ports {mem_wdata[18]}]
set_load -pin_load 0.0334 [get_ports {mem_wdata[17]}]
set_load -pin_load 0.0334 [get_ports {mem_wdata[16]}]
set_load -pin_load 0.0334 [get_ports {mem_wdata[15]}]
set_load -pin_load 0.0334 [get_ports {mem_wdata[14]}]
set_load -pin_load 0.0334 [get_ports {mem_wdata[13]}]
set_load -pin_load 0.0334 [get_ports {mem_wdata[12]}]
set_load -pin_load 0.0334 [get_ports {mem_wdata[11]}]
set_load -pin_load 0.0334 [get_ports {mem_wdata[10]}]
set_load -pin_load 0.0334 [get_ports {mem_wdata[9]}]
set_load -pin_load 0.0334 [get_ports {mem_wdata[8]}]
set_load -pin_load 0.0334 [get_ports {mem_wdata[7]}]
set_load -pin_load 0.0334 [get_ports {mem_wdata[6]}]
set_load -pin_load 0.0334 [get_ports {mem_wdata[5]}]
set_load -pin_load 0.0334 [get_ports {mem_wdata[4]}]
set_load -pin_load 0.0334 [get_ports {mem_wdata[3]}]
set_load -pin_load 0.0334 [get_ports {mem_wdata[2]}]
set_load -pin_load 0.0334 [get_ports {mem_wdata[1]}]
set_load -pin_load 0.0334 [get_ports {mem_wdata[0]}]
set_load -pin_load 0.0334 [get_ports {pcRegister[31]}]
set_load -pin_load 0.0334 [get_ports {pcRegister[30]}]
set_load -pin_load 0.0334 [get_ports {pcRegister[29]}]
set_load -pin_load 0.0334 [get_ports {pcRegister[28]}]
set_load -pin_load 0.0334 [get_ports {pcRegister[27]}]
set_load -pin_load 0.0334 [get_ports {pcRegister[26]}]
set_load -pin_load 0.0334 [get_ports {pcRegister[25]}]
set_load -pin_load 0.0334 [get_ports {pcRegister[24]}]
set_load -pin_load 0.0334 [get_ports {pcRegister[23]}]
set_load -pin_load 0.0334 [get_ports {pcRegister[22]}]
set_load -pin_load 0.0334 [get_ports {pcRegister[21]}]
set_load -pin_load 0.0334 [get_ports {pcRegister[20]}]
set_load -pin_load 0.0334 [get_ports {pcRegister[19]}]
set_load -pin_load 0.0334 [get_ports {pcRegister[18]}]
set_load -pin_load 0.0334 [get_ports {pcRegister[17]}]
set_load -pin_load 0.0334 [get_ports {pcRegister[16]}]
set_load -pin_load 0.0334 [get_ports {pcRegister[15]}]
set_load -pin_load 0.0334 [get_ports {pcRegister[14]}]
set_load -pin_load 0.0334 [get_ports {pcRegister[13]}]
set_load -pin_load 0.0334 [get_ports {pcRegister[12]}]
set_load -pin_load 0.0334 [get_ports {pcRegister[11]}]
set_load -pin_load 0.0334 [get_ports {pcRegister[10]}]
set_load -pin_load 0.0334 [get_ports {pcRegister[9]}]
set_load -pin_load 0.0334 [get_ports {pcRegister[8]}]
set_load -pin_load 0.0334 [get_ports {pcRegister[7]}]
set_load -pin_load 0.0334 [get_ports {pcRegister[6]}]
set_load -pin_load 0.0334 [get_ports {pcRegister[5]}]
set_load -pin_load 0.0334 [get_ports {pcRegister[4]}]
set_load -pin_load 0.0334 [get_ports {pcRegister[3]}]
set_load -pin_load 0.0334 [get_ports {pcRegister[2]}]
set_load -pin_load 0.0334 [get_ports {pcRegister[1]}]
set_load -pin_load 0.0334 [get_ports {pcRegister[0]}]
set_load -pin_load 0.0334 [get_ports {red[7]}]
set_load -pin_load 0.0334 [get_ports {red[6]}]
set_load -pin_load 0.0334 [get_ports {red[5]}]
set_load -pin_load 0.0334 [get_ports {red[4]}]
set_load -pin_load 0.0334 [get_ports {red[3]}]
set_load -pin_load 0.0334 [get_ports {red[2]}]
set_load -pin_load 0.0334 [get_ports {red[1]}]
set_load -pin_load 0.0334 [get_ports {red[0]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {clk}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {reset}]
###############################################################################
# Design Rules
###############################################################################
set_max_transition 0.7500 [current_design]
set_max_capacitance 0.2000 [current_design]
set_max_fanout 10.0000 [current_design]
