// Auto-generated by LibreLane
module soc_top(
`ifdef USE_POWER_PINS
  inout VGND,
  inout VPWR,
`endif
  input clk,
  input reset,
  output Hsync,
  output Vsync,
  output[7:0] red,
  output[7:0] green,
  output[7:0] blue,
  output[31:0] pcRegister,
  output[31:0] mem_addr,
  output[31:0] mem_wdata,
  output mem_write,
  output mem_read,
  output cpu_stall,
  output display_enable
);
endmodule
